<?php
/**
 * OrderProgressResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Complyforce API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@devowl.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.82
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DevOwl\ComplyforceApiClient\Model;

use \ArrayAccess;
use \DevOwl\ComplyforceApiClient\ObjectSerializer;

/**
 * OrderProgressResponse Class Doc Comment
 *
 * @category Class
 * @description Order progress response
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderProgressResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'OrderProgressResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'orderUuid' => '',
        'status' => '',
        'sitemapDiscoveredUrls' => '',
        'processedUrls' => '',
        'totalUrls' => '',
        'error' => '\DevOwl\ComplyforceApiClient\Model\OrderProgressResponseError'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'orderUuid' => 'uuid',
        'status' => null,
        'sitemapDiscoveredUrls' => null,
        'processedUrls' => null,
        'totalUrls' => null,
        'error' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'orderUuid' => 'orderUuid',
        'status' => 'status',
        'sitemapDiscoveredUrls' => 'sitemapDiscoveredUrls',
        'processedUrls' => 'processedUrls',
        'totalUrls' => 'totalUrls',
        'error' => 'error'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'orderUuid' => 'setOrderUuid',
        'status' => 'setStatus',
        'sitemapDiscoveredUrls' => 'setSitemapDiscoveredUrls',
        'processedUrls' => 'setProcessedUrls',
        'totalUrls' => 'setTotalUrls',
        'error' => 'setError'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'orderUuid' => 'getOrderUuid',
        'status' => 'getStatus',
        'sitemapDiscoveredUrls' => 'getSitemapDiscoveredUrls',
        'processedUrls' => 'getProcessedUrls',
        'totalUrls' => 'getTotalUrls',
        'error' => 'getError'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['orderUuid'] = isset($data['orderUuid']) ? $data['orderUuid'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['sitemapDiscoveredUrls'] = isset($data['sitemapDiscoveredUrls']) ? $data['sitemapDiscoveredUrls'] : null;
        $this->container['processedUrls'] = isset($data['processedUrls']) ? $data['processedUrls'] : null;
        $this->container['totalUrls'] = isset($data['totalUrls']) ? $data['totalUrls'] : null;
        $this->container['error'] = isset($data['error']) ? $data['error'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['orderUuid'] === null) {
            $invalidProperties[] = "'orderUuid' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['processedUrls'] === null) {
            $invalidProperties[] = "'processedUrls' can't be null";
        }
        if ($this->container['totalUrls'] === null) {
            $invalidProperties[] = "'totalUrls' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets orderUuid
     *
     * @return 
     */
    public function getOrderUuid()
    {
        return $this->container['orderUuid'];
    }

    /**
     * Sets orderUuid
     *
     * @param  $orderUuid orderUuid
     *
     * @return $this
     */
    public function setOrderUuid($orderUuid)
    {
        $this->container['orderUuid'] = $orderUuid;

        return $this;
    }

    /**
     * Gets status
     *
     * @return 
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param  $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets sitemapDiscoveredUrls
     *
     * @return 
     */
    public function getSitemapDiscoveredUrls()
    {
        return $this->container['sitemapDiscoveredUrls'];
    }

    /**
     * Sets sitemapDiscoveredUrls
     *
     * @param  $sitemapDiscoveredUrls sitemapDiscoveredUrls
     *
     * @return $this
     */
    public function setSitemapDiscoveredUrls($sitemapDiscoveredUrls)
    {
        $this->container['sitemapDiscoveredUrls'] = $sitemapDiscoveredUrls;

        return $this;
    }

    /**
     * Gets processedUrls
     *
     * @return 
     */
    public function getProcessedUrls()
    {
        return $this->container['processedUrls'];
    }

    /**
     * Sets processedUrls
     *
     * @param  $processedUrls processedUrls
     *
     * @return $this
     */
    public function setProcessedUrls($processedUrls)
    {
        $this->container['processedUrls'] = $processedUrls;

        return $this;
    }

    /**
     * Gets totalUrls
     *
     * @return 
     */
    public function getTotalUrls()
    {
        return $this->container['totalUrls'];
    }

    /**
     * Sets totalUrls
     *
     * @param  $totalUrls totalUrls
     *
     * @return $this
     */
    public function setTotalUrls($totalUrls)
    {
        $this->container['totalUrls'] = $totalUrls;

        return $this;
    }

    /**
     * Gets error
     *
     * @return \DevOwl\ComplyforceApiClient\Model\OrderProgressResponseError
     */
    public function getError()
    {
        return $this->container['error'];
    }

    /**
     * Sets error
     *
     * @param \DevOwl\ComplyforceApiClient\Model\OrderProgressResponseError $error error
     *
     * @return $this
     */
    public function setError($error)
    {
        $this->container['error'] = $error;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
