<?php
/**
 * OrderPosted
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Complyforce API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@devowl.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DevOwl\ComplyforceApiClient\Model;

use \ArrayAccess;
use \DevOwl\ComplyforceApiClient\ObjectSerializer;

/**
 * OrderPosted Class Doc Comment
 *
 * @category Class
 * @description Posted order entity
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderPosted implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'OrderPosted';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'uuid' => '',
        'scanType' => '',
        'scanFeaturesRequested' => '',
        'scanDomain' => '',
        'scanUrlsRequested' => '',
        'scanUrlsLimit' => '',
        'scanPriority' => '',
        'status' => '',
        'createdAt' => '',
        'statusUpdates' => ''
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'uuid' => 'uuid',
        'scanType' => null,
        'scanFeaturesRequested' => null,
        'scanDomain' => null,
        'scanUrlsRequested' => null,
        'scanUrlsLimit' => null,
        'scanPriority' => null,
        'status' => null,
        'createdAt' => 'date-time',
        'statusUpdates' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uuid' => 'uuid',
        'scanType' => 'scanType',
        'scanFeaturesRequested' => 'scanFeaturesRequested',
        'scanDomain' => 'scanDomain',
        'scanUrlsRequested' => 'scanUrlsRequested',
        'scanUrlsLimit' => 'scanUrlsLimit',
        'scanPriority' => 'scanPriority',
        'status' => 'status',
        'createdAt' => 'createdAt',
        'statusUpdates' => 'statusUpdates'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uuid' => 'setUuid',
        'scanType' => 'setScanType',
        'scanFeaturesRequested' => 'setScanFeaturesRequested',
        'scanDomain' => 'setScanDomain',
        'scanUrlsRequested' => 'setScanUrlsRequested',
        'scanUrlsLimit' => 'setScanUrlsLimit',
        'scanPriority' => 'setScanPriority',
        'status' => 'setStatus',
        'createdAt' => 'setCreatedAt',
        'statusUpdates' => 'setStatusUpdates'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uuid' => 'getUuid',
        'scanType' => 'getScanType',
        'scanFeaturesRequested' => 'getScanFeaturesRequested',
        'scanDomain' => 'getScanDomain',
        'scanUrlsRequested' => 'getScanUrlsRequested',
        'scanUrlsLimit' => 'getScanUrlsLimit',
        'scanPriority' => 'getScanPriority',
        'status' => 'getStatus',
        'createdAt' => 'getCreatedAt',
        'statusUpdates' => 'getStatusUpdates'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['uuid'] = isset($data['uuid']) ? $data['uuid'] : null;
        $this->container['scanType'] = isset($data['scanType']) ? $data['scanType'] : null;
        $this->container['scanFeaturesRequested'] = isset($data['scanFeaturesRequested']) ? $data['scanFeaturesRequested'] : null;
        $this->container['scanDomain'] = isset($data['scanDomain']) ? $data['scanDomain'] : null;
        $this->container['scanUrlsRequested'] = isset($data['scanUrlsRequested']) ? $data['scanUrlsRequested'] : null;
        $this->container['scanUrlsLimit'] = isset($data['scanUrlsLimit']) ? $data['scanUrlsLimit'] : null;
        $this->container['scanPriority'] = isset($data['scanPriority']) ? $data['scanPriority'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['createdAt'] = isset($data['createdAt']) ? $data['createdAt'] : null;
        $this->container['statusUpdates'] = isset($data['statusUpdates']) ? $data['statusUpdates'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['uuid'] === null) {
            $invalidProperties[] = "'uuid' can't be null";
        }
        if ($this->container['scanType'] === null) {
            $invalidProperties[] = "'scanType' can't be null";
        }
        if ($this->container['scanFeaturesRequested'] === null) {
            $invalidProperties[] = "'scanFeaturesRequested' can't be null";
        }
        if ($this->container['scanDomain'] === null) {
            $invalidProperties[] = "'scanDomain' can't be null";
        }
        if ($this->container['scanUrlsRequested'] === null) {
            $invalidProperties[] = "'scanUrlsRequested' can't be null";
        }
        if ($this->container['scanPriority'] === null) {
            $invalidProperties[] = "'scanPriority' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['statusUpdates'] === null) {
            $invalidProperties[] = "'statusUpdates' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uuid
     *
     * @return 
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param  $uuid uuid
     *
     * @return $this
     */
    public function setUuid($uuid)
    {
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets scanType
     *
     * @return 
     */
    public function getScanType()
    {
        return $this->container['scanType'];
    }

    /**
     * Sets scanType
     *
     * @param  $scanType scanType
     *
     * @return $this
     */
    public function setScanType($scanType)
    {
        $this->container['scanType'] = $scanType;

        return $this;
    }

    /**
     * Gets scanFeaturesRequested
     *
     * @return 
     */
    public function getScanFeaturesRequested()
    {
        return $this->container['scanFeaturesRequested'];
    }

    /**
     * Sets scanFeaturesRequested
     *
     * @param  $scanFeaturesRequested scanFeaturesRequested
     *
     * @return $this
     */
    public function setScanFeaturesRequested($scanFeaturesRequested)
    {
        $this->container['scanFeaturesRequested'] = $scanFeaturesRequested;

        return $this;
    }

    /**
     * Gets scanDomain
     *
     * @return 
     */
    public function getScanDomain()
    {
        return $this->container['scanDomain'];
    }

    /**
     * Sets scanDomain
     *
     * @param  $scanDomain scanDomain
     *
     * @return $this
     */
    public function setScanDomain($scanDomain)
    {
        $this->container['scanDomain'] = $scanDomain;

        return $this;
    }

    /**
     * Gets scanUrlsRequested
     *
     * @return 
     */
    public function getScanUrlsRequested()
    {
        return $this->container['scanUrlsRequested'];
    }

    /**
     * Sets scanUrlsRequested
     *
     * @param  $scanUrlsRequested Array of URLs to scan. Duplicate URLs are automatically removed when multiple URLs are provided.
     *
     * @return $this
     */
    public function setScanUrlsRequested($scanUrlsRequested)
    {
        $this->container['scanUrlsRequested'] = $scanUrlsRequested;

        return $this;
    }

    /**
     * Gets scanUrlsLimit
     *
     * @return 
     */
    public function getScanUrlsLimit()
    {
        return $this->container['scanUrlsLimit'];
    }

    /**
     * Sets scanUrlsLimit
     *
     * @param  $scanUrlsLimit Maximum number of URLs/pages to scan for all-pages scans (default: 500, max: 10000).
     *
     * @return $this
     */
    public function setScanUrlsLimit($scanUrlsLimit)
    {
        $this->container['scanUrlsLimit'] = $scanUrlsLimit;

        return $this;
    }

    /**
     * Gets scanPriority
     *
     * @return 
     */
    public function getScanPriority()
    {
        return $this->container['scanPriority'];
    }

    /**
     * Sets scanPriority
     *
     * @param  $scanPriority scanPriority
     *
     * @return $this
     */
    public function setScanPriority($scanPriority)
    {
        $this->container['scanPriority'] = $scanPriority;

        return $this;
    }

    /**
     * Gets status
     *
     * @return 
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param  $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return 
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param  $createdAt createdAt
     *
     * @return $this
     */
    public function setCreatedAt($createdAt)
    {
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets statusUpdates
     *
     * @return 
     */
    public function getStatusUpdates()
    {
        return $this->container['statusUpdates'];
    }

    /**
     * Sets statusUpdates
     *
     * @param  $statusUpdates statusUpdates
     *
     * @return $this
     */
    public function setStatusUpdates($statusUpdates)
    {
        $this->container['statusUpdates'] = $statusUpdates;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
