<?php
/**
 * OrderReportGetResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Complyforce API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@devowl.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DevOwl\ComplyforceApiClient\Model;

use \ArrayAccess;
use \DevOwl\ComplyforceApiClient\ObjectSerializer;

/**
 * OrderReportGetResponse Class Doc Comment
 *
 * @category Class
 * @description Get order report entity
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderReportGetResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'OrderReportGetResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'uuid' => '',
        'scanType' => '',
        'scanDomain' => '',
        'scanUrlsExecuted' => '',
        'createdAt' => '',
        'vendorBrand' => '\DevOwl\ComplyforceApiClient\Model\OrderReportGetResponseVendorBrand',
        'report' => '\DevOwl\ComplyforceApiClient\Model\OrderReportGetResponseReport',
        'latestStatusUpdate' => '\DevOwl\ComplyforceApiClient\Model\OrderReportGetResponseLatestStatusUpdate'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'uuid' => 'uuid',
        'scanType' => null,
        'scanDomain' => null,
        'scanUrlsExecuted' => null,
        'createdAt' => 'date-time',
        'vendorBrand' => null,
        'report' => null,
        'latestStatusUpdate' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uuid' => 'uuid',
        'scanType' => 'scanType',
        'scanDomain' => 'scanDomain',
        'scanUrlsExecuted' => 'scanUrlsExecuted',
        'createdAt' => 'createdAt',
        'vendorBrand' => 'vendorBrand',
        'report' => 'report',
        'latestStatusUpdate' => 'latestStatusUpdate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uuid' => 'setUuid',
        'scanType' => 'setScanType',
        'scanDomain' => 'setScanDomain',
        'scanUrlsExecuted' => 'setScanUrlsExecuted',
        'createdAt' => 'setCreatedAt',
        'vendorBrand' => 'setVendorBrand',
        'report' => 'setReport',
        'latestStatusUpdate' => 'setLatestStatusUpdate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uuid' => 'getUuid',
        'scanType' => 'getScanType',
        'scanDomain' => 'getScanDomain',
        'scanUrlsExecuted' => 'getScanUrlsExecuted',
        'createdAt' => 'getCreatedAt',
        'vendorBrand' => 'getVendorBrand',
        'report' => 'getReport',
        'latestStatusUpdate' => 'getLatestStatusUpdate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['uuid'] = isset($data['uuid']) ? $data['uuid'] : null;
        $this->container['scanType'] = isset($data['scanType']) ? $data['scanType'] : null;
        $this->container['scanDomain'] = isset($data['scanDomain']) ? $data['scanDomain'] : null;
        $this->container['scanUrlsExecuted'] = isset($data['scanUrlsExecuted']) ? $data['scanUrlsExecuted'] : null;
        $this->container['createdAt'] = isset($data['createdAt']) ? $data['createdAt'] : null;
        $this->container['vendorBrand'] = isset($data['vendorBrand']) ? $data['vendorBrand'] : null;
        $this->container['report'] = isset($data['report']) ? $data['report'] : null;
        $this->container['latestStatusUpdate'] = isset($data['latestStatusUpdate']) ? $data['latestStatusUpdate'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['uuid'] === null) {
            $invalidProperties[] = "'uuid' can't be null";
        }
        if ($this->container['scanType'] === null) {
            $invalidProperties[] = "'scanType' can't be null";
        }
        if ($this->container['scanDomain'] === null) {
            $invalidProperties[] = "'scanDomain' can't be null";
        }
        if ($this->container['vendorBrand'] === null) {
            $invalidProperties[] = "'vendorBrand' can't be null";
        }
        if ($this->container['report'] === null) {
            $invalidProperties[] = "'report' can't be null";
        }
        if ($this->container['latestStatusUpdate'] === null) {
            $invalidProperties[] = "'latestStatusUpdate' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uuid
     *
     * @return 
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param  $uuid uuid
     *
     * @return $this
     */
    public function setUuid($uuid)
    {
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets scanType
     *
     * @return 
     */
    public function getScanType()
    {
        return $this->container['scanType'];
    }

    /**
     * Sets scanType
     *
     * @param  $scanType scanType
     *
     * @return $this
     */
    public function setScanType($scanType)
    {
        $this->container['scanType'] = $scanType;

        return $this;
    }

    /**
     * Gets scanDomain
     *
     * @return 
     */
    public function getScanDomain()
    {
        return $this->container['scanDomain'];
    }

    /**
     * Sets scanDomain
     *
     * @param  $scanDomain scanDomain
     *
     * @return $this
     */
    public function setScanDomain($scanDomain)
    {
        $this->container['scanDomain'] = $scanDomain;

        return $this;
    }

    /**
     * Gets scanUrlsExecuted
     *
     * @return 
     */
    public function getScanUrlsExecuted()
    {
        return $this->container['scanUrlsExecuted'];
    }

    /**
     * Sets scanUrlsExecuted
     *
     * @param  $scanUrlsExecuted scanUrlsExecuted
     *
     * @return $this
     */
    public function setScanUrlsExecuted($scanUrlsExecuted)
    {
        $this->container['scanUrlsExecuted'] = $scanUrlsExecuted;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return 
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param  $createdAt createdAt
     *
     * @return $this
     */
    public function setCreatedAt($createdAt)
    {
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets vendorBrand
     *
     * @return \DevOwl\ComplyforceApiClient\Model\OrderReportGetResponseVendorBrand
     */
    public function getVendorBrand()
    {
        return $this->container['vendorBrand'];
    }

    /**
     * Sets vendorBrand
     *
     * @param \DevOwl\ComplyforceApiClient\Model\OrderReportGetResponseVendorBrand $vendorBrand vendorBrand
     *
     * @return $this
     */
    public function setVendorBrand($vendorBrand)
    {
        $this->container['vendorBrand'] = $vendorBrand;

        return $this;
    }

    /**
     * Gets report
     *
     * @return \DevOwl\ComplyforceApiClient\Model\OrderReportGetResponseReport
     */
    public function getReport()
    {
        return $this->container['report'];
    }

    /**
     * Sets report
     *
     * @param \DevOwl\ComplyforceApiClient\Model\OrderReportGetResponseReport $report report
     *
     * @return $this
     */
    public function setReport($report)
    {
        $this->container['report'] = $report;

        return $this;
    }

    /**
     * Gets latestStatusUpdate
     *
     * @return \DevOwl\ComplyforceApiClient\Model\OrderReportGetResponseLatestStatusUpdate
     */
    public function getLatestStatusUpdate()
    {
        return $this->container['latestStatusUpdate'];
    }

    /**
     * Sets latestStatusUpdate
     *
     * @param \DevOwl\ComplyforceApiClient\Model\OrderReportGetResponseLatestStatusUpdate $latestStatusUpdate latestStatusUpdate
     *
     * @return $this
     */
    public function setLatestStatusUpdate($latestStatusUpdate)
    {
        $this->container['latestStatusUpdate'] = $latestStatusUpdate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
