<?php
/**
 * OrderListItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Complyforce API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@devowl.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DevOwl\ComplyforceApiClient\Model;

use \ArrayAccess;
use \DevOwl\ComplyforceApiClient\ObjectSerializer;

/**
 * OrderListItem Class Doc Comment
 *
 * @category Class
 * @description Order summary for list view
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderListItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'OrderListItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'uuid' => '',
        'id' => '',
        'scanType' => '',
        'scanDomain' => '',
        'scanUrlsRequestedCount' => '',
        'reportScanUrlsExecutedCount' => '',
        'report' => '\DevOwl\ComplyforceApiClient\Model\OrderGetResponseReport',
        'status' => '',
        'errorType' => '',
        'createdAt' => '',
        'lastStatusUpdate' => '\DevOwl\ComplyforceApiClient\Model\OrderListItemLastStatusUpdate',
        'reportAvailability' => '',
        'reportAvailableUntil' => '',
        'vendorBrand' => '\DevOwl\ComplyforceApiClient\Model\OrderListItemVendorBrand',
        'vendorBrandChannel' => '\DevOwl\ComplyforceApiClient\Model\OrderListItemVendorBrand'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'uuid' => 'uuid',
        'id' => null,
        'scanType' => null,
        'scanDomain' => null,
        'scanUrlsRequestedCount' => null,
        'reportScanUrlsExecutedCount' => null,
        'report' => null,
        'status' => null,
        'errorType' => null,
        'createdAt' => 'date-time',
        'lastStatusUpdate' => null,
        'reportAvailability' => null,
        'reportAvailableUntil' => 'date-time',
        'vendorBrand' => null,
        'vendorBrandChannel' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uuid' => 'uuid',
        'id' => 'id',
        'scanType' => 'scanType',
        'scanDomain' => 'scanDomain',
        'scanUrlsRequestedCount' => 'scanUrlsRequestedCount',
        'reportScanUrlsExecutedCount' => 'reportScanUrlsExecutedCount',
        'report' => 'report',
        'status' => 'status',
        'errorType' => 'errorType',
        'createdAt' => 'createdAt',
        'lastStatusUpdate' => 'lastStatusUpdate',
        'reportAvailability' => 'reportAvailability',
        'reportAvailableUntil' => 'reportAvailableUntil',
        'vendorBrand' => 'vendorBrand',
        'vendorBrandChannel' => 'vendorBrandChannel'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uuid' => 'setUuid',
        'id' => 'setId',
        'scanType' => 'setScanType',
        'scanDomain' => 'setScanDomain',
        'scanUrlsRequestedCount' => 'setScanUrlsRequestedCount',
        'reportScanUrlsExecutedCount' => 'setReportScanUrlsExecutedCount',
        'report' => 'setReport',
        'status' => 'setStatus',
        'errorType' => 'setErrorType',
        'createdAt' => 'setCreatedAt',
        'lastStatusUpdate' => 'setLastStatusUpdate',
        'reportAvailability' => 'setReportAvailability',
        'reportAvailableUntil' => 'setReportAvailableUntil',
        'vendorBrand' => 'setVendorBrand',
        'vendorBrandChannel' => 'setVendorBrandChannel'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uuid' => 'getUuid',
        'id' => 'getId',
        'scanType' => 'getScanType',
        'scanDomain' => 'getScanDomain',
        'scanUrlsRequestedCount' => 'getScanUrlsRequestedCount',
        'reportScanUrlsExecutedCount' => 'getReportScanUrlsExecutedCount',
        'report' => 'getReport',
        'status' => 'getStatus',
        'errorType' => 'getErrorType',
        'createdAt' => 'getCreatedAt',
        'lastStatusUpdate' => 'getLastStatusUpdate',
        'reportAvailability' => 'getReportAvailability',
        'reportAvailableUntil' => 'getReportAvailableUntil',
        'vendorBrand' => 'getVendorBrand',
        'vendorBrandChannel' => 'getVendorBrandChannel'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['uuid'] = isset($data['uuid']) ? $data['uuid'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['scanType'] = isset($data['scanType']) ? $data['scanType'] : null;
        $this->container['scanDomain'] = isset($data['scanDomain']) ? $data['scanDomain'] : null;
        $this->container['scanUrlsRequestedCount'] = isset($data['scanUrlsRequestedCount']) ? $data['scanUrlsRequestedCount'] : null;
        $this->container['reportScanUrlsExecutedCount'] = isset($data['reportScanUrlsExecutedCount']) ? $data['reportScanUrlsExecutedCount'] : null;
        $this->container['report'] = isset($data['report']) ? $data['report'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['errorType'] = isset($data['errorType']) ? $data['errorType'] : null;
        $this->container['createdAt'] = isset($data['createdAt']) ? $data['createdAt'] : null;
        $this->container['lastStatusUpdate'] = isset($data['lastStatusUpdate']) ? $data['lastStatusUpdate'] : null;
        $this->container['reportAvailability'] = isset($data['reportAvailability']) ? $data['reportAvailability'] : null;
        $this->container['reportAvailableUntil'] = isset($data['reportAvailableUntil']) ? $data['reportAvailableUntil'] : null;
        $this->container['vendorBrand'] = isset($data['vendorBrand']) ? $data['vendorBrand'] : null;
        $this->container['vendorBrandChannel'] = isset($data['vendorBrandChannel']) ? $data['vendorBrandChannel'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['uuid'] === null) {
            $invalidProperties[] = "'uuid' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['scanType'] === null) {
            $invalidProperties[] = "'scanType' can't be null";
        }
        if ($this->container['scanDomain'] === null) {
            $invalidProperties[] = "'scanDomain' can't be null";
        }
        if ($this->container['scanUrlsRequestedCount'] === null) {
            $invalidProperties[] = "'scanUrlsRequestedCount' can't be null";
        }
        if ($this->container['reportScanUrlsExecutedCount'] === null) {
            $invalidProperties[] = "'reportScanUrlsExecutedCount' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['reportAvailability'] === null) {
            $invalidProperties[] = "'reportAvailability' can't be null";
        }
        if ($this->container['vendorBrand'] === null) {
            $invalidProperties[] = "'vendorBrand' can't be null";
        }
        if ($this->container['vendorBrandChannel'] === null) {
            $invalidProperties[] = "'vendorBrandChannel' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uuid
     *
     * @return 
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param  $uuid uuid
     *
     * @return $this
     */
    public function setUuid($uuid)
    {
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets id
     *
     * @return 
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param  $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets scanType
     *
     * @return 
     */
    public function getScanType()
    {
        return $this->container['scanType'];
    }

    /**
     * Sets scanType
     *
     * @param  $scanType scanType
     *
     * @return $this
     */
    public function setScanType($scanType)
    {
        $this->container['scanType'] = $scanType;

        return $this;
    }

    /**
     * Gets scanDomain
     *
     * @return 
     */
    public function getScanDomain()
    {
        return $this->container['scanDomain'];
    }

    /**
     * Sets scanDomain
     *
     * @param  $scanDomain scanDomain
     *
     * @return $this
     */
    public function setScanDomain($scanDomain)
    {
        $this->container['scanDomain'] = $scanDomain;

        return $this;
    }

    /**
     * Gets scanUrlsRequestedCount
     *
     * @return 
     */
    public function getScanUrlsRequestedCount()
    {
        return $this->container['scanUrlsRequestedCount'];
    }

    /**
     * Sets scanUrlsRequestedCount
     *
     * @param  $scanUrlsRequestedCount scanUrlsRequestedCount
     *
     * @return $this
     */
    public function setScanUrlsRequestedCount($scanUrlsRequestedCount)
    {
        $this->container['scanUrlsRequestedCount'] = $scanUrlsRequestedCount;

        return $this;
    }

    /**
     * Gets reportScanUrlsExecutedCount
     *
     * @return 
     */
    public function getReportScanUrlsExecutedCount()
    {
        return $this->container['reportScanUrlsExecutedCount'];
    }

    /**
     * Sets reportScanUrlsExecutedCount
     *
     * @param  $reportScanUrlsExecutedCount reportScanUrlsExecutedCount
     *
     * @return $this
     */
    public function setReportScanUrlsExecutedCount($reportScanUrlsExecutedCount)
    {
        $this->container['reportScanUrlsExecutedCount'] = $reportScanUrlsExecutedCount;

        return $this;
    }

    /**
     * Gets report
     *
     * @return \DevOwl\ComplyforceApiClient\Model\OrderGetResponseReport
     */
    public function getReport()
    {
        return $this->container['report'];
    }

    /**
     * Sets report
     *
     * @param \DevOwl\ComplyforceApiClient\Model\OrderGetResponseReport $report report
     *
     * @return $this
     */
    public function setReport($report)
    {
        $this->container['report'] = $report;

        return $this;
    }

    /**
     * Gets status
     *
     * @return 
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param  $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets errorType
     *
     * @return 
     */
    public function getErrorType()
    {
        return $this->container['errorType'];
    }

    /**
     * Sets errorType
     *
     * @param  $errorType errorType
     *
     * @return $this
     */
    public function setErrorType($errorType)
    {
        $this->container['errorType'] = $errorType;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return 
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param  $createdAt createdAt
     *
     * @return $this
     */
    public function setCreatedAt($createdAt)
    {
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets lastStatusUpdate
     *
     * @return \DevOwl\ComplyforceApiClient\Model\OrderListItemLastStatusUpdate
     */
    public function getLastStatusUpdate()
    {
        return $this->container['lastStatusUpdate'];
    }

    /**
     * Sets lastStatusUpdate
     *
     * @param \DevOwl\ComplyforceApiClient\Model\OrderListItemLastStatusUpdate $lastStatusUpdate lastStatusUpdate
     *
     * @return $this
     */
    public function setLastStatusUpdate($lastStatusUpdate)
    {
        $this->container['lastStatusUpdate'] = $lastStatusUpdate;

        return $this;
    }

    /**
     * Gets reportAvailability
     *
     * @return 
     */
    public function getReportAvailability()
    {
        return $this->container['reportAvailability'];
    }

    /**
     * Sets reportAvailability
     *
     * @param  $reportAvailability reportAvailability
     *
     * @return $this
     */
    public function setReportAvailability($reportAvailability)
    {
        $this->container['reportAvailability'] = $reportAvailability;

        return $this;
    }

    /**
     * Gets reportAvailableUntil
     *
     * @return 
     */
    public function getReportAvailableUntil()
    {
        return $this->container['reportAvailableUntil'];
    }

    /**
     * Sets reportAvailableUntil
     *
     * @param  $reportAvailableUntil reportAvailableUntil
     *
     * @return $this
     */
    public function setReportAvailableUntil($reportAvailableUntil)
    {
        $this->container['reportAvailableUntil'] = $reportAvailableUntil;

        return $this;
    }

    /**
     * Gets vendorBrand
     *
     * @return \DevOwl\ComplyforceApiClient\Model\OrderListItemVendorBrand
     */
    public function getVendorBrand()
    {
        return $this->container['vendorBrand'];
    }

    /**
     * Sets vendorBrand
     *
     * @param \DevOwl\ComplyforceApiClient\Model\OrderListItemVendorBrand $vendorBrand vendorBrand
     *
     * @return $this
     */
    public function setVendorBrand($vendorBrand)
    {
        $this->container['vendorBrand'] = $vendorBrand;

        return $this;
    }

    /**
     * Gets vendorBrandChannel
     *
     * @return \DevOwl\ComplyforceApiClient\Model\OrderListItemVendorBrand
     */
    public function getVendorBrandChannel()
    {
        return $this->container['vendorBrandChannel'];
    }

    /**
     * Sets vendorBrandChannel
     *
     * @param \DevOwl\ComplyforceApiClient\Model\OrderListItemVendorBrand $vendorBrandChannel vendorBrandChannel
     *
     * @return $this
     */
    public function setVendorBrandChannel($vendorBrandChannel)
    {
        $this->container['vendorBrandChannel'] = $vendorBrandChannel;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
