<?php
/**
 * OrderCreate
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Complyforce API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@devowl.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.82
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DevOwl\ComplyforceApiClient\Model;

use \ArrayAccess;
use \DevOwl\ComplyforceApiClient\ObjectSerializer;

/**
 * OrderCreate Class Doc Comment
 *
 * @category Class
 * @description Create order request with channel, scan type and URLs.
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderCreate implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'OrderCreate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'scanType' => '',
        'scanUrlsRequested' => '',
        'scanUrlsLimit' => '',
        'traceEnabled' => '',
        'channel' => '\DevOwl\ComplyforceApiClient\Model\OrderCreateChannel'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'scanType' => null,
        'scanUrlsRequested' => null,
        'scanUrlsLimit' => null,
        'traceEnabled' => null,
        'channel' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'scanType' => 'scanType',
        'scanUrlsRequested' => 'scanUrlsRequested',
        'scanUrlsLimit' => 'scanUrlsLimit',
        'traceEnabled' => 'traceEnabled',
        'channel' => 'channel'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'scanType' => 'setScanType',
        'scanUrlsRequested' => 'setScanUrlsRequested',
        'scanUrlsLimit' => 'setScanUrlsLimit',
        'traceEnabled' => 'setTraceEnabled',
        'channel' => 'setChannel'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'scanType' => 'getScanType',
        'scanUrlsRequested' => 'getScanUrlsRequested',
        'scanUrlsLimit' => 'getScanUrlsLimit',
        'traceEnabled' => 'getTraceEnabled',
        'channel' => 'getChannel'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['scanType'] = isset($data['scanType']) ? $data['scanType'] : null;
        $this->container['scanUrlsRequested'] = isset($data['scanUrlsRequested']) ? $data['scanUrlsRequested'] : null;
        $this->container['scanUrlsLimit'] = isset($data['scanUrlsLimit']) ? $data['scanUrlsLimit'] : null;
        $this->container['traceEnabled'] = isset($data['traceEnabled']) ? $data['traceEnabled'] : null;
        $this->container['channel'] = isset($data['channel']) ? $data['channel'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['scanType'] === null) {
            $invalidProperties[] = "'scanType' can't be null";
        }
        if ($this->container['scanUrlsRequested'] === null) {
            $invalidProperties[] = "'scanUrlsRequested' can't be null";
        }
        if ($this->container['channel'] === null) {
            $invalidProperties[] = "'channel' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets scanType
     *
     * @return 
     */
    public function getScanType()
    {
        return $this->container['scanType'];
    }

    /**
     * Sets scanType
     *
     * @param  $scanType scanType
     *
     * @return $this
     */
    public function setScanType($scanType)
    {
        $this->container['scanType'] = $scanType;

        return $this;
    }

    /**
     * Gets scanUrlsRequested
     *
     * @return 
     */
    public function getScanUrlsRequested()
    {
        return $this->container['scanUrlsRequested'];
    }

    /**
     * Sets scanUrlsRequested
     *
     * @param  $scanUrlsRequested Array of URLs to scan. Duplicate URLs are automatically removed when multiple URLs are provided.
     *
     * @return $this
     */
    public function setScanUrlsRequested($scanUrlsRequested)
    {
        $this->container['scanUrlsRequested'] = $scanUrlsRequested;

        return $this;
    }

    /**
     * Gets scanUrlsLimit
     *
     * @return 
     */
    public function getScanUrlsLimit()
    {
        return $this->container['scanUrlsLimit'];
    }

    /**
     * Sets scanUrlsLimit
     *
     * @param  $scanUrlsLimit Maximum number of URLs/pages to scan for all-pages scans (default: 500, max: 10000).
     *
     * @return $this
     */
    public function setScanUrlsLimit($scanUrlsLimit)
    {
        $this->container['scanUrlsLimit'] = $scanUrlsLimit;

        return $this;
    }

    /**
     * Gets traceEnabled
     *
     * @return 
     */
    public function getTraceEnabled()
    {
        return $this->container['traceEnabled'];
    }

    /**
     * Sets traceEnabled
     *
     * @param  $traceEnabled Admin only. When true, keeps detailed diagnostic captures for this order after the scan finishes.
     *
     * @return $this
     */
    public function setTraceEnabled($traceEnabled)
    {
        $this->container['traceEnabled'] = $traceEnabled;

        return $this;
    }

    /**
     * Gets channel
     *
     * @return \DevOwl\ComplyforceApiClient\Model\OrderCreateChannel
     */
    public function getChannel()
    {
        return $this->container['channel'];
    }

    /**
     * Sets channel
     *
     * @param \DevOwl\ComplyforceApiClient\Model\OrderCreateChannel $channel channel
     *
     * @return $this
     */
    public function setChannel($channel)
    {
        $this->container['channel'] = $channel;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
