<?php
/**
 * OrderReportGetResponseVendorBrandProperties
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Complyforce API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@devowl.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DevOwl\ComplyforceApiClient\Model;

use \ArrayAccess;
use \DevOwl\ComplyforceApiClient\ObjectSerializer;

/**
 * OrderReportGetResponseVendorBrandProperties Class Doc Comment
 *
 * @category Class
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderReportGetResponseVendorBrandProperties implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'OrderReportGetResponse_vendorBrand_properties';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => '',
        'language' => '',
        'brandName' => '',
        'colorPrimary' => '',
        'whiteLabel' => '',
        'realCookieBannerAds' => '',
        'legalNoticeUrl' => '',
        'legalPrivacyPolicyUrl' => '',
        'legalDisclaimerLegalAdviceOverwrite' => '',
        'translations' => '',
        'revision' => '',
        'createdAt' => ''
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'language' => null,
        'brandName' => null,
        'colorPrimary' => null,
        'whiteLabel' => null,
        'realCookieBannerAds' => null,
        'legalNoticeUrl' => null,
        'legalPrivacyPolicyUrl' => null,
        'legalDisclaimerLegalAdviceOverwrite' => null,
        'translations' => null,
        'revision' => null,
        'createdAt' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'language' => 'language',
        'brandName' => 'brandName',
        'colorPrimary' => 'colorPrimary',
        'whiteLabel' => 'whiteLabel',
        'realCookieBannerAds' => 'realCookieBannerAds',
        'legalNoticeUrl' => 'legalNoticeUrl',
        'legalPrivacyPolicyUrl' => 'legalPrivacyPolicyUrl',
        'legalDisclaimerLegalAdviceOverwrite' => 'legalDisclaimerLegalAdviceOverwrite',
        'translations' => 'translations',
        'revision' => 'revision',
        'createdAt' => 'createdAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'language' => 'setLanguage',
        'brandName' => 'setBrandName',
        'colorPrimary' => 'setColorPrimary',
        'whiteLabel' => 'setWhiteLabel',
        'realCookieBannerAds' => 'setRealCookieBannerAds',
        'legalNoticeUrl' => 'setLegalNoticeUrl',
        'legalPrivacyPolicyUrl' => 'setLegalPrivacyPolicyUrl',
        'legalDisclaimerLegalAdviceOverwrite' => 'setLegalDisclaimerLegalAdviceOverwrite',
        'translations' => 'setTranslations',
        'revision' => 'setRevision',
        'createdAt' => 'setCreatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'language' => 'getLanguage',
        'brandName' => 'getBrandName',
        'colorPrimary' => 'getColorPrimary',
        'whiteLabel' => 'getWhiteLabel',
        'realCookieBannerAds' => 'getRealCookieBannerAds',
        'legalNoticeUrl' => 'getLegalNoticeUrl',
        'legalPrivacyPolicyUrl' => 'getLegalPrivacyPolicyUrl',
        'legalDisclaimerLegalAdviceOverwrite' => 'getLegalDisclaimerLegalAdviceOverwrite',
        'translations' => 'getTranslations',
        'revision' => 'getRevision',
        'createdAt' => 'getCreatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['language'] = isset($data['language']) ? $data['language'] : null;
        $this->container['brandName'] = isset($data['brandName']) ? $data['brandName'] : null;
        $this->container['colorPrimary'] = isset($data['colorPrimary']) ? $data['colorPrimary'] : null;
        $this->container['whiteLabel'] = isset($data['whiteLabel']) ? $data['whiteLabel'] : null;
        $this->container['realCookieBannerAds'] = isset($data['realCookieBannerAds']) ? $data['realCookieBannerAds'] : null;
        $this->container['legalNoticeUrl'] = isset($data['legalNoticeUrl']) ? $data['legalNoticeUrl'] : null;
        $this->container['legalPrivacyPolicyUrl'] = isset($data['legalPrivacyPolicyUrl']) ? $data['legalPrivacyPolicyUrl'] : null;
        $this->container['legalDisclaimerLegalAdviceOverwrite'] = isset($data['legalDisclaimerLegalAdviceOverwrite']) ? $data['legalDisclaimerLegalAdviceOverwrite'] : null;
        $this->container['translations'] = isset($data['translations']) ? $data['translations'] : null;
        $this->container['revision'] = isset($data['revision']) ? $data['revision'] : null;
        $this->container['createdAt'] = isset($data['createdAt']) ? $data['createdAt'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return 
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param  $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets language
     *
     * @return 
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param  $language language
     *
     * @return $this
     */
    public function setLanguage($language)
    {
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets brandName
     *
     * @return 
     */
    public function getBrandName()
    {
        return $this->container['brandName'];
    }

    /**
     * Sets brandName
     *
     * @param  $brandName brandName
     *
     * @return $this
     */
    public function setBrandName($brandName)
    {
        $this->container['brandName'] = $brandName;

        return $this;
    }

    /**
     * Gets colorPrimary
     *
     * @return 
     */
    public function getColorPrimary()
    {
        return $this->container['colorPrimary'];
    }

    /**
     * Sets colorPrimary
     *
     * @param  $colorPrimary colorPrimary
     *
     * @return $this
     */
    public function setColorPrimary($colorPrimary)
    {
        $this->container['colorPrimary'] = $colorPrimary;

        return $this;
    }

    /**
     * Gets whiteLabel
     *
     * @return 
     */
    public function getWhiteLabel()
    {
        return $this->container['whiteLabel'];
    }

    /**
     * Sets whiteLabel
     *
     * @param  $whiteLabel whiteLabel
     *
     * @return $this
     */
    public function setWhiteLabel($whiteLabel)
    {
        $this->container['whiteLabel'] = $whiteLabel;

        return $this;
    }

    /**
     * Gets realCookieBannerAds
     *
     * @return 
     */
    public function getRealCookieBannerAds()
    {
        return $this->container['realCookieBannerAds'];
    }

    /**
     * Sets realCookieBannerAds
     *
     * @param  $realCookieBannerAds realCookieBannerAds
     *
     * @return $this
     */
    public function setRealCookieBannerAds($realCookieBannerAds)
    {
        $this->container['realCookieBannerAds'] = $realCookieBannerAds;

        return $this;
    }

    /**
     * Gets legalNoticeUrl
     *
     * @return 
     */
    public function getLegalNoticeUrl()
    {
        return $this->container['legalNoticeUrl'];
    }

    /**
     * Sets legalNoticeUrl
     *
     * @param  $legalNoticeUrl legalNoticeUrl
     *
     * @return $this
     */
    public function setLegalNoticeUrl($legalNoticeUrl)
    {
        $this->container['legalNoticeUrl'] = $legalNoticeUrl;

        return $this;
    }

    /**
     * Gets legalPrivacyPolicyUrl
     *
     * @return 
     */
    public function getLegalPrivacyPolicyUrl()
    {
        return $this->container['legalPrivacyPolicyUrl'];
    }

    /**
     * Sets legalPrivacyPolicyUrl
     *
     * @param  $legalPrivacyPolicyUrl legalPrivacyPolicyUrl
     *
     * @return $this
     */
    public function setLegalPrivacyPolicyUrl($legalPrivacyPolicyUrl)
    {
        $this->container['legalPrivacyPolicyUrl'] = $legalPrivacyPolicyUrl;

        return $this;
    }

    /**
     * Gets legalDisclaimerLegalAdviceOverwrite
     *
     * @return 
     */
    public function getLegalDisclaimerLegalAdviceOverwrite()
    {
        return $this->container['legalDisclaimerLegalAdviceOverwrite'];
    }

    /**
     * Sets legalDisclaimerLegalAdviceOverwrite
     *
     * @param  $legalDisclaimerLegalAdviceOverwrite legalDisclaimerLegalAdviceOverwrite
     *
     * @return $this
     */
    public function setLegalDisclaimerLegalAdviceOverwrite($legalDisclaimerLegalAdviceOverwrite)
    {
        $this->container['legalDisclaimerLegalAdviceOverwrite'] = $legalDisclaimerLegalAdviceOverwrite;

        return $this;
    }

    /**
     * Gets translations
     *
     * @return 
     */
    public function getTranslations()
    {
        return $this->container['translations'];
    }

    /**
     * Sets translations
     *
     * @param  $translations translations
     *
     * @return $this
     */
    public function setTranslations($translations)
    {
        $this->container['translations'] = $translations;

        return $this;
    }

    /**
     * Gets revision
     *
     * @return 
     */
    public function getRevision()
    {
        return $this->container['revision'];
    }

    /**
     * Sets revision
     *
     * @param  $revision revision
     *
     * @return $this
     */
    public function setRevision($revision)
    {
        $this->container['revision'] = $revision;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return 
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param  $createdAt createdAt
     *
     * @return $this
     */
    public function setCreatedAt($createdAt)
    {
        $this->container['createdAt'] = $createdAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
