<?php
/**
 * ScanUrlResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Complyforce API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@devowl.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.82
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DevOwl\ComplyforceApiClient\Model;

use \ArrayAccess;
use \DevOwl\ComplyforceApiClient\ObjectSerializer;

/**
 * ScanUrlResult Class Doc Comment
 *
 * @category Class
 * @description Scan artefact fields for one scanned page URL.
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScanUrlResult implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ScanUrlResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'beforeConsentAcceptAll' => '',
        'afterConsentAcceptAll' => '',
        'trace' => '',
        'errorName' => '',
        'errorMessage' => '',
        'errorStack' => '',
        'processedAt' => ''
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'beforeConsentAcceptAll' => null,
        'afterConsentAcceptAll' => null,
        'trace' => null,
        'errorName' => null,
        'errorMessage' => null,
        'errorStack' => null,
        'processedAt' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'beforeConsentAcceptAll' => 'beforeConsentAcceptAll',
        'afterConsentAcceptAll' => 'afterConsentAcceptAll',
        'trace' => 'trace',
        'errorName' => 'errorName',
        'errorMessage' => 'errorMessage',
        'errorStack' => 'errorStack',
        'processedAt' => 'processedAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'beforeConsentAcceptAll' => 'setBeforeConsentAcceptAll',
        'afterConsentAcceptAll' => 'setAfterConsentAcceptAll',
        'trace' => 'setTrace',
        'errorName' => 'setErrorName',
        'errorMessage' => 'setErrorMessage',
        'errorStack' => 'setErrorStack',
        'processedAt' => 'setProcessedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'beforeConsentAcceptAll' => 'getBeforeConsentAcceptAll',
        'afterConsentAcceptAll' => 'getAfterConsentAcceptAll',
        'trace' => 'getTrace',
        'errorName' => 'getErrorName',
        'errorMessage' => 'getErrorMessage',
        'errorStack' => 'getErrorStack',
        'processedAt' => 'getProcessedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['beforeConsentAcceptAll'] = isset($data['beforeConsentAcceptAll']) ? $data['beforeConsentAcceptAll'] : null;
        $this->container['afterConsentAcceptAll'] = isset($data['afterConsentAcceptAll']) ? $data['afterConsentAcceptAll'] : null;
        $this->container['trace'] = isset($data['trace']) ? $data['trace'] : null;
        $this->container['errorName'] = isset($data['errorName']) ? $data['errorName'] : null;
        $this->container['errorMessage'] = isset($data['errorMessage']) ? $data['errorMessage'] : null;
        $this->container['errorStack'] = isset($data['errorStack']) ? $data['errorStack'] : null;
        $this->container['processedAt'] = isset($data['processedAt']) ? $data['processedAt'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets beforeConsentAcceptAll
     *
     * @return 
     */
    public function getBeforeConsentAcceptAll()
    {
        return $this->container['beforeConsentAcceptAll'];
    }

    /**
     * Sets beforeConsentAcceptAll
     *
     * @param  $beforeConsentAcceptAll Signed S3 URL for the before-consent (accept-all) capture.
     *
     * @return $this
     */
    public function setBeforeConsentAcceptAll($beforeConsentAcceptAll)
    {
        $this->container['beforeConsentAcceptAll'] = $beforeConsentAcceptAll;

        return $this;
    }

    /**
     * Gets afterConsentAcceptAll
     *
     * @return 
     */
    public function getAfterConsentAcceptAll()
    {
        return $this->container['afterConsentAcceptAll'];
    }

    /**
     * Sets afterConsentAcceptAll
     *
     * @param  $afterConsentAcceptAll Signed S3 URL for the after-consent (accept-all) capture.
     *
     * @return $this
     */
    public function setAfterConsentAcceptAll($afterConsentAcceptAll)
    {
        $this->container['afterConsentAcceptAll'] = $afterConsentAcceptAll;

        return $this;
    }

    /**
     * Gets trace
     *
     * @return 
     */
    public function getTrace()
    {
        return $this->container['trace'];
    }

    /**
     * Sets trace
     *
     * @param  $trace Signed S3 URL for the crawl trace artefact.
     *
     * @return $this
     */
    public function setTrace($trace)
    {
        $this->container['trace'] = $trace;

        return $this;
    }

    /**
     * Gets errorName
     *
     * @return 
     */
    public function getErrorName()
    {
        return $this->container['errorName'];
    }

    /**
     * Sets errorName
     *
     * @param  $errorName Error name when the URL scan failed.
     *
     * @return $this
     */
    public function setErrorName($errorName)
    {
        $this->container['errorName'] = $errorName;

        return $this;
    }

    /**
     * Gets errorMessage
     *
     * @return 
     */
    public function getErrorMessage()
    {
        return $this->container['errorMessage'];
    }

    /**
     * Sets errorMessage
     *
     * @param  $errorMessage Error message when the URL scan failed.
     *
     * @return $this
     */
    public function setErrorMessage($errorMessage)
    {
        $this->container['errorMessage'] = $errorMessage;

        return $this;
    }

    /**
     * Gets errorStack
     *
     * @return 
     */
    public function getErrorStack()
    {
        return $this->container['errorStack'];
    }

    /**
     * Sets errorStack
     *
     * @param  $errorStack Error stack when the URL scan failed.
     *
     * @return $this
     */
    public function setErrorStack($errorStack)
    {
        $this->container['errorStack'] = $errorStack;

        return $this;
    }

    /**
     * Gets processedAt
     *
     * @return 
     */
    public function getProcessedAt()
    {
        return $this->container['processedAt'];
    }

    /**
     * Sets processedAt
     *
     * @param  $processedAt ISO timestamp when this URL was processed.
     *
     * @return $this
     */
    public function setProcessedAt($processedAt)
    {
        $this->container['processedAt'] = $processedAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
