<?php
/**
 * BrandPropertiesBody1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Complyforce API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@devowl.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.75
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DevOwl\ComplyforceApiClient;

use PHPUnit\Framework\TestCase;

/**
 * BrandPropertiesBody1Test Class Doc Comment
 *
 * @category    Class
 * @description BrandPropertiesBody1
 * @package     DevOwl\ComplyforceApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BrandPropertiesBody1Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BrandPropertiesBody1"
     */
    public function testBrandPropertiesBody1()
    {
    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {
    }

    /**
     * Test attribute "keys"
     */
    public function testPropertyKeys()
    {
    }
}
