<?php
/**
 * CursorPaginationResponseMetadataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Complyforce API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@devowl.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DevOwl\ComplyforceApiClient;

use PHPUnit\Framework\TestCase;

/**
 * CursorPaginationResponseMetadataTest Class Doc Comment
 *
 * @category    Class
 * @description Cursor-based pagination metadata for list responses.
 * @package     DevOwl\ComplyforceApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CursorPaginationResponseMetadataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CursorPaginationResponseMetadata"
     */
    public function testCursorPaginationResponseMetadata()
    {
    }

    /**
     * Test attribute "cursor"
     */
    public function testPropertyCursor()
    {
    }

    /**
     * Test attribute "nextCursor"
     */
    public function testPropertyNextCursor()
    {
    }

    /**
     * Test attribute "dataCount"
     */
    public function testPropertyDataCount()
    {
    }
}
