<?php
/**
 * OrderListItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Complyforce API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@devowl.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DevOwl\ComplyforceApiClient;

use PHPUnit\Framework\TestCase;

/**
 * OrderListItemTest Class Doc Comment
 *
 * @category    Class
 * @description Order summary for list view
 * @package     DevOwl\ComplyforceApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderListItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrderListItem"
     */
    public function testOrderListItem()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "scanType"
     */
    public function testPropertyScanType()
    {
    }

    /**
     * Test attribute "scanDomain"
     */
    public function testPropertyScanDomain()
    {
    }

    /**
     * Test attribute "scanUrlsRequestedCount"
     */
    public function testPropertyScanUrlsRequestedCount()
    {
    }

    /**
     * Test attribute "reportScanUrlsExecutedCount"
     */
    public function testPropertyReportScanUrlsExecutedCount()
    {
    }

    /**
     * Test attribute "report"
     */
    public function testPropertyReport()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "errorType"
     */
    public function testPropertyErrorType()
    {
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "lastStatusUpdate"
     */
    public function testPropertyLastStatusUpdate()
    {
    }

    /**
     * Test attribute "reportAvailability"
     */
    public function testPropertyReportAvailability()
    {
    }

    /**
     * Test attribute "reportAvailableUntil"
     */
    public function testPropertyReportAvailableUntil()
    {
    }

    /**
     * Test attribute "vendorBrand"
     */
    public function testPropertyVendorBrand()
    {
    }

    /**
     * Test attribute "vendorBrandChannel"
     */
    public function testPropertyVendorBrandChannel()
    {
    }
}
