<?php
/**
 * OrderReportGetResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Complyforce API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@devowl.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.77
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DevOwl\ComplyforceApiClient;

use PHPUnit\Framework\TestCase;

/**
 * OrderReportGetResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Get order report entity
 * @package     DevOwl\ComplyforceApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderReportGetResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrderReportGetResponse"
     */
    public function testOrderReportGetResponse()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "scanType"
     */
    public function testPropertyScanType()
    {
    }

    /**
     * Test attribute "scanDomain"
     */
    public function testPropertyScanDomain()
    {
    }

    /**
     * Test attribute "scanUrlsExecuted"
     */
    public function testPropertyScanUrlsExecuted()
    {
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "vendorBrand"
     */
    public function testPropertyVendorBrand()
    {
    }

    /**
     * Test attribute "report"
     */
    public function testPropertyReport()
    {
    }

    /**
     * Test attribute "latestStatusUpdate"
     */
    public function testPropertyLatestStatusUpdate()
    {
    }
}
