<?php
/**
 * OrderReportGetResponseReportTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Complyforce API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@devowl.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.78
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DevOwl\ComplyforceApiClient;

use PHPUnit\Framework\TestCase;

/**
 * OrderReportGetResponseReportTest Class Doc Comment
 *
 * @category    Class
 * @description OrderReportGetResponseReport
 * @package     DevOwl\ComplyforceApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderReportGetResponseReportTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrderReportGetResponseReport"
     */
    public function testOrderReportGetResponseReport()
    {
    }

    /**
     * Test attribute "reportUrl"
     */
    public function testPropertyReportUrl()
    {
    }

    /**
     * Test attribute "dataProtectionViolationsFound"
     */
    public function testPropertyDataProtectionViolationsFound()
    {
    }

    /**
     * Test attribute "riskScore"
     */
    public function testPropertyRiskScore()
    {
    }
}
