<?php
/**
 * VendorApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Complyforce API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@devowl.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.75
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DevOwl\ComplyforceApiClient;

use DevOwl\ComplyforceApiClient\Configuration;
use DevOwl\ComplyforceApiClient\ApiException;
use DevOwl\ComplyforceApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * VendorApiTest Class Doc Comment
 *
 * @category Class
 * @package  DevOwl\ComplyforceApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VendorApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for vendorContractPost
     *
     * Update vendor contract.
     *
     */
    public function testVendorContractPost()
    {
    }

    /**
     * Test case for vendorInvoiceAddressPost
     *
     * Update invoice address.
     *
     */
    public function testVendorInvoiceAddressPost()
    {
    }

    /**
     * Test case for vendorPost
     *
     * Create a new vendor.
     *
     */
    public function testVendorPost()
    {
    }

    /**
     * Test case for vendorPut
     *
     * Update a vendor.
     *
     */
    public function testVendorPut()
    {
    }

    /**
     * Test case for vendorsGet
     *
     * Get all vendors.
     *
     */
    public function testVendorsGet()
    {
    }
}
